name: CI / build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Create .env.local
        run: |
          cat > .env.local <<'EOF'
          NEXT_PUBLIC_SUPABASE_URL=${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ vars.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          EOF

      - name: Install deps
        run: npm install --prefer-offline --no-audit

      - name: Build
        env:
          CI: true
          NEXT_TELEMETRY_DISABLED: 1
        run: npm run build
